// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: format.proto

#include "format.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace proto {
class ZSTD_Compression_filterDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ZSTD_Compression_filter>
      _instance;
} _ZSTD_Compression_filter_default_instance_;
class AES256_Encryption_filterDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AES256_Encryption_filter>
      _instance;
} _AES256_Encryption_filter_default_instance_;
class FilterDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Filter>
      _instance;
  const ::proto::ZSTD_Compression_filter* zstd_compression_;
  const ::proto::AES256_Encryption_filter* aes_encryption_;
} _Filter_default_instance_;
class RefDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Ref>
      _instance;
} _Ref_default_instance_;
class Fs_recordDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Fs_record>
      _instance;
} _Fs_record_default_instance_;
class Fs_stateDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Fs_state>
      _instance;
} _Fs_state_default_instance_;
class File_descDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<File_desc>
      _instance;
} _File_desc_default_instance_;
class Ref_countDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Ref_count>
      _instance;
} _Ref_count_default_instance_;
class CatalogueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Catalogue>
      _instance;
} _Catalogue_default_instance_;
class Catalog_headerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Catalog_header>
      _instance;
} _Catalog_header_default_instance_;
}  // namespace proto
namespace protobuf_format_2eproto {
void InitDefaultsZSTD_Compression_filterImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::proto::_ZSTD_Compression_filter_default_instance_;
    new (ptr) ::proto::ZSTD_Compression_filter();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::ZSTD_Compression_filter::InitAsDefaultInstance();
}

void InitDefaultsZSTD_Compression_filter() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsZSTD_Compression_filterImpl);
}

void InitDefaultsAES256_Encryption_filterImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::proto::_AES256_Encryption_filter_default_instance_;
    new (ptr) ::proto::AES256_Encryption_filter();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::AES256_Encryption_filter::InitAsDefaultInstance();
}

void InitDefaultsAES256_Encryption_filter() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsAES256_Encryption_filterImpl);
}

void InitDefaultsFilterImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_format_2eproto::InitDefaultsZSTD_Compression_filter();
  protobuf_format_2eproto::InitDefaultsAES256_Encryption_filter();
  {
    void* ptr = &::proto::_Filter_default_instance_;
    new (ptr) ::proto::Filter();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Filter::InitAsDefaultInstance();
}

void InitDefaultsFilter() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFilterImpl);
}

void InitDefaultsRefImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::proto::_Ref_default_instance_;
    new (ptr) ::proto::Ref();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Ref::InitAsDefaultInstance();
}

void InitDefaultsRef() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsRefImpl);
}

void InitDefaultsFs_recordImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_format_2eproto::InitDefaultsRef();
  {
    void* ptr = &::proto::_Fs_record_default_instance_;
    new (ptr) ::proto::Fs_record();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Fs_record::InitAsDefaultInstance();
}

void InitDefaultsFs_record() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFs_recordImpl);
}

void InitDefaultsFs_stateImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_format_2eproto::InitDefaultsFs_record();
  {
    void* ptr = &::proto::_Fs_state_default_instance_;
    new (ptr) ::proto::Fs_state();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Fs_state::InitAsDefaultInstance();
}

void InitDefaultsFs_state() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFs_stateImpl);
}

void InitDefaultsFile_descImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_format_2eproto::InitDefaultsFilter();
  protobuf_format_2eproto::InitDefaultsRef_count();
  {
    void* ptr = &::proto::_File_desc_default_instance_;
    new (ptr) ::proto::File_desc();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::File_desc::InitAsDefaultInstance();
}

void InitDefaultsFile_desc() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFile_descImpl);
}

void InitDefaultsRef_countImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::proto::_Ref_count_default_instance_;
    new (ptr) ::proto::Ref_count();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Ref_count::InitAsDefaultInstance();
}

void InitDefaultsRef_count() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsRef_countImpl);
}

void InitDefaultsCatalogueImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_format_2eproto::InitDefaultsFile_desc();
  {
    void* ptr = &::proto::_Catalogue_default_instance_;
    new (ptr) ::proto::Catalogue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Catalogue::InitAsDefaultInstance();
}

void InitDefaultsCatalogue() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCatalogueImpl);
}

void InitDefaultsCatalog_headerImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_format_2eproto::InitDefaultsFilter();
  {
    void* ptr = &::proto::_Catalog_header_default_instance_;
    new (ptr) ::proto::Catalog_header();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Catalog_header::InitAsDefaultInstance();
}

void InitDefaultsCatalog_header() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCatalog_headerImpl);
}

}  // namespace protobuf_format_2eproto
namespace proto {
bool File_type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ZSTD_Compression_filter::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ZSTD_Compression_filter::ZSTD_Compression_filter()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsZSTD_Compression_filter();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.ZSTD_Compression_filter)
}
ZSTD_Compression_filter::ZSTD_Compression_filter(const ZSTD_Compression_filter& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.ZSTD_Compression_filter)
}

void ZSTD_Compression_filter::SharedCtor() {
  _cached_size_ = 0;
}

ZSTD_Compression_filter::~ZSTD_Compression_filter() {
  // @@protoc_insertion_point(destructor:proto.ZSTD_Compression_filter)
  SharedDtor();
}

void ZSTD_Compression_filter::SharedDtor() {
}

void ZSTD_Compression_filter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ZSTD_Compression_filter& ZSTD_Compression_filter::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsZSTD_Compression_filter();
  return *internal_default_instance();
}

ZSTD_Compression_filter* ZSTD_Compression_filter::New(::google::protobuf::Arena* arena) const {
  ZSTD_Compression_filter* n = new ZSTD_Compression_filter;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ZSTD_Compression_filter::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ZSTD_Compression_filter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool ZSTD_Compression_filter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.ZSTD_Compression_filter)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(
        input, tag, &unknown_fields_stream));
  }
success:
  // @@protoc_insertion_point(parse_success:proto.ZSTD_Compression_filter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.ZSTD_Compression_filter)
  return false;
#undef DO_
}

void ZSTD_Compression_filter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.ZSTD_Compression_filter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.ZSTD_Compression_filter)
}

size_t ZSTD_Compression_filter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.ZSTD_Compression_filter)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ZSTD_Compression_filter::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ZSTD_Compression_filter*>(&from));
}

void ZSTD_Compression_filter::MergeFrom(const ZSTD_Compression_filter& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.ZSTD_Compression_filter)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ZSTD_Compression_filter::CopyFrom(const ZSTD_Compression_filter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.ZSTD_Compression_filter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ZSTD_Compression_filter::IsInitialized() const {
  return true;
}

void ZSTD_Compression_filter::Swap(ZSTD_Compression_filter* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ZSTD_Compression_filter::InternalSwap(ZSTD_Compression_filter* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string ZSTD_Compression_filter::GetTypeName() const {
  return "proto.ZSTD_Compression_filter";
}


// ===================================================================

void AES256_Encryption_filter::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AES256_Encryption_filter::kSaltFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AES256_Encryption_filter::AES256_Encryption_filter()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsAES256_Encryption_filter();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.AES256_Encryption_filter)
}
AES256_Encryption_filter::AES256_Encryption_filter(const AES256_Encryption_filter& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  salt_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.salt().size() > 0) {
    salt_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.salt_);
  }
  // @@protoc_insertion_point(copy_constructor:proto.AES256_Encryption_filter)
}

void AES256_Encryption_filter::SharedCtor() {
  salt_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

AES256_Encryption_filter::~AES256_Encryption_filter() {
  // @@protoc_insertion_point(destructor:proto.AES256_Encryption_filter)
  SharedDtor();
}

void AES256_Encryption_filter::SharedDtor() {
  salt_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AES256_Encryption_filter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const AES256_Encryption_filter& AES256_Encryption_filter::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsAES256_Encryption_filter();
  return *internal_default_instance();
}

AES256_Encryption_filter* AES256_Encryption_filter::New(::google::protobuf::Arena* arena) const {
  AES256_Encryption_filter* n = new AES256_Encryption_filter;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AES256_Encryption_filter::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.AES256_Encryption_filter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  salt_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool AES256_Encryption_filter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.AES256_Encryption_filter)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes salt = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_salt()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.AES256_Encryption_filter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.AES256_Encryption_filter)
  return false;
#undef DO_
}

void AES256_Encryption_filter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.AES256_Encryption_filter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes salt = 1;
  if (this->salt().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->salt(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.AES256_Encryption_filter)
}

size_t AES256_Encryption_filter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.AES256_Encryption_filter)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // bytes salt = 1;
  if (this->salt().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->salt());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AES256_Encryption_filter::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const AES256_Encryption_filter*>(&from));
}

void AES256_Encryption_filter::MergeFrom(const AES256_Encryption_filter& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.AES256_Encryption_filter)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.salt().size() > 0) {

    salt_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.salt_);
  }
}

void AES256_Encryption_filter::CopyFrom(const AES256_Encryption_filter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.AES256_Encryption_filter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AES256_Encryption_filter::IsInitialized() const {
  return true;
}

void AES256_Encryption_filter::Swap(AES256_Encryption_filter* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AES256_Encryption_filter::InternalSwap(AES256_Encryption_filter* other) {
  using std::swap;
  salt_.Swap(&other->salt_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string AES256_Encryption_filter::GetTypeName() const {
  return "proto.AES256_Encryption_filter";
}


// ===================================================================

void Filter::InitAsDefaultInstance() {
}
void Filter::set_allocated_zstd_compression(::proto::ZSTD_Compression_filter* zstd_compression) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_filter();
  if (zstd_compression) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      zstd_compression = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, zstd_compression, submessage_arena);
    }
    set_has_zstd_compression();
    filter_.zstd_compression_ = zstd_compression;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Filter.zstd_compression)
}
void Filter::set_allocated_aes_encryption(::proto::AES256_Encryption_filter* aes_encryption) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_filter();
  if (aes_encryption) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      aes_encryption = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, aes_encryption, submessage_arena);
    }
    set_has_aes_encryption();
    filter_.aes_encryption_ = aes_encryption;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Filter.aes_encryption)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Filter::kZstdCompressionFieldNumber;
const int Filter::kAesEncryptionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Filter::Filter()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsFilter();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Filter)
}
Filter::Filter(const Filter& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_filter();
  switch (from.filter_case()) {
    case kZstdCompression: {
      mutable_zstd_compression()->::proto::ZSTD_Compression_filter::MergeFrom(from.zstd_compression());
      break;
    }
    case kAesEncryption: {
      mutable_aes_encryption()->::proto::AES256_Encryption_filter::MergeFrom(from.aes_encryption());
      break;
    }
    case FILTER_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:proto.Filter)
}

void Filter::SharedCtor() {
  clear_has_filter();
  _cached_size_ = 0;
}

Filter::~Filter() {
  // @@protoc_insertion_point(destructor:proto.Filter)
  SharedDtor();
}

void Filter::SharedDtor() {
  if (has_filter()) {
    clear_filter();
  }
}

void Filter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Filter& Filter::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsFilter();
  return *internal_default_instance();
}

Filter* Filter::New(::google::protobuf::Arena* arena) const {
  Filter* n = new Filter;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Filter::clear_filter() {
// @@protoc_insertion_point(one_of_clear_start:proto.Filter)
  switch (filter_case()) {
    case kZstdCompression: {
      delete filter_.zstd_compression_;
      break;
    }
    case kAesEncryption: {
      delete filter_.aes_encryption_;
      break;
    }
    case FILTER_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = FILTER_NOT_SET;
}


void Filter::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Filter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_filter();
  _internal_metadata_.Clear();
}

bool Filter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.Filter)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .proto.ZSTD_Compression_filter zstd_compression = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_zstd_compression()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .proto.AES256_Encryption_filter aes_encryption = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_aes_encryption()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Filter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Filter)
  return false;
#undef DO_
}

void Filter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Filter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .proto.ZSTD_Compression_filter zstd_compression = 1;
  if (has_zstd_compression()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, *filter_.zstd_compression_, output);
  }

  // .proto.AES256_Encryption_filter aes_encryption = 2;
  if (has_aes_encryption()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *filter_.aes_encryption_, output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.Filter)
}

size_t Filter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Filter)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  switch (filter_case()) {
    // .proto.ZSTD_Compression_filter zstd_compression = 1;
    case kZstdCompression: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *filter_.zstd_compression_);
      break;
    }
    // .proto.AES256_Encryption_filter aes_encryption = 2;
    case kAesEncryption: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *filter_.aes_encryption_);
      break;
    }
    case FILTER_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Filter::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Filter*>(&from));
}

void Filter::MergeFrom(const Filter& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Filter)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.filter_case()) {
    case kZstdCompression: {
      mutable_zstd_compression()->::proto::ZSTD_Compression_filter::MergeFrom(from.zstd_compression());
      break;
    }
    case kAesEncryption: {
      mutable_aes_encryption()->::proto::AES256_Encryption_filter::MergeFrom(from.aes_encryption());
      break;
    }
    case FILTER_NOT_SET: {
      break;
    }
  }
}

void Filter::CopyFrom(const Filter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Filter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Filter::IsInitialized() const {
  return true;
}

void Filter::Swap(Filter* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Filter::InternalSwap(Filter* other) {
  using std::swap;
  swap(filter_, other->filter_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Filter::GetTypeName() const {
  return "proto.Filter";
}


// ===================================================================

void Ref::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Ref::kContentFnameFieldNumber;
const int Ref::kFromFieldNumber;
const int Ref::kToFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Ref::Ref()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsRef();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Ref)
}
Ref::Ref(const Ref& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_fname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content_fname().size() > 0) {
    content_fname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_fname_);
  }
  ::memcpy(&from_, &from.from_,
    static_cast<size_t>(reinterpret_cast<char*>(&to_) -
    reinterpret_cast<char*>(&from_)) + sizeof(to_));
  // @@protoc_insertion_point(copy_constructor:proto.Ref)
}

void Ref::SharedCtor() {
  content_fname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&from_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&to_) -
      reinterpret_cast<char*>(&from_)) + sizeof(to_));
  _cached_size_ = 0;
}

Ref::~Ref() {
  // @@protoc_insertion_point(destructor:proto.Ref)
  SharedDtor();
}

void Ref::SharedDtor() {
  content_fname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Ref::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Ref& Ref::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsRef();
  return *internal_default_instance();
}

Ref* Ref::New(::google::protobuf::Arena* arena) const {
  Ref* n = new Ref;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Ref::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Ref)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  content_fname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&from_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&to_) -
      reinterpret_cast<char*>(&from_)) + sizeof(to_));
  _internal_metadata_.Clear();
}

bool Ref::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.Ref)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string content_fname = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content_fname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content_fname().data(), static_cast<int>(this->content_fname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.Ref.content_fname"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 from = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &from_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 to = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &to_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Ref)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Ref)
  return false;
#undef DO_
}

void Ref::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Ref)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content_fname = 1;
  if (this->content_fname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content_fname().data(), static_cast<int>(this->content_fname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.Ref.content_fname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->content_fname(), output);
  }

  // uint64 from = 2;
  if (this->from() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->from(), output);
  }

  // uint64 to = 3;
  if (this->to() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->to(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.Ref)
}

size_t Ref::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Ref)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string content_fname = 1;
  if (this->content_fname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content_fname());
  }

  // uint64 from = 2;
  if (this->from() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->from());
  }

  // uint64 to = 3;
  if (this->to() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->to());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Ref::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Ref*>(&from));
}

void Ref::MergeFrom(const Ref& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Ref)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.content_fname().size() > 0) {

    content_fname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_fname_);
  }
  if (from.from() != 0) {
    set_from(from.from());
  }
  if (from.to() != 0) {
    set_to(from.to());
  }
}

void Ref::CopyFrom(const Ref& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Ref)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ref::IsInitialized() const {
  return true;
}

void Ref::Swap(Ref* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Ref::InternalSwap(Ref* other) {
  using std::swap;
  content_fname_.Swap(&other->content_fname_);
  swap(from_, other->from_);
  swap(to_, other->to_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Ref::GetTypeName() const {
  return "proto.Ref";
}


// ===================================================================

void Fs_record::InitAsDefaultInstance() {
  ::proto::_Fs_record_default_instance_._instance.get_mutable()->ref_ = const_cast< ::proto::Ref*>(
      ::proto::Ref::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Fs_record::kPathnameFieldNumber;
const int Fs_record::kUnixPermissionsFieldNumber;
const int Fs_record::kTypeFieldNumber;
const int Fs_record::kModifiedSecondsFieldNumber;
const int Fs_record::kRefFieldNumber;
const int Fs_record::kSymlinkTargetFieldNumber;
const int Fs_record::kPosixAclFieldNumber;
const int Fs_record::kPosixDefaultAclFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Fs_record::Fs_record()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsFs_record();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Fs_record)
}
Fs_record::Fs_record(const Fs_record& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  pathname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.pathname().size() > 0) {
    pathname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pathname_);
  }
  symlink_target_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.symlink_target().size() > 0) {
    symlink_target_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.symlink_target_);
  }
  posix_acl_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.posix_acl().size() > 0) {
    posix_acl_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.posix_acl_);
  }
  posix_default_acl_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.posix_default_acl().size() > 0) {
    posix_default_acl_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.posix_default_acl_);
  }
  if (from.has_ref()) {
    ref_ = new ::proto::Ref(*from.ref_);
  } else {
    ref_ = NULL;
  }
  ::memcpy(&unix_permissions_, &from.unix_permissions_,
    static_cast<size_t>(reinterpret_cast<char*>(&modified_seconds_) -
    reinterpret_cast<char*>(&unix_permissions_)) + sizeof(modified_seconds_));
  // @@protoc_insertion_point(copy_constructor:proto.Fs_record)
}

void Fs_record::SharedCtor() {
  pathname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  symlink_target_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  posix_acl_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  posix_default_acl_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&ref_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&modified_seconds_) -
      reinterpret_cast<char*>(&ref_)) + sizeof(modified_seconds_));
  _cached_size_ = 0;
}

Fs_record::~Fs_record() {
  // @@protoc_insertion_point(destructor:proto.Fs_record)
  SharedDtor();
}

void Fs_record::SharedDtor() {
  pathname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  symlink_target_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  posix_acl_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  posix_default_acl_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete ref_;
}

void Fs_record::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Fs_record& Fs_record::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsFs_record();
  return *internal_default_instance();
}

Fs_record* Fs_record::New(::google::protobuf::Arena* arena) const {
  Fs_record* n = new Fs_record;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Fs_record::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Fs_record)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  pathname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  symlink_target_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  posix_acl_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  posix_default_acl_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && ref_ != NULL) {
    delete ref_;
  }
  ref_ = NULL;
  ::memset(&unix_permissions_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&modified_seconds_) -
      reinterpret_cast<char*>(&unix_permissions_)) + sizeof(modified_seconds_));
  _internal_metadata_.Clear();
}

bool Fs_record::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.Fs_record)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string pathname = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pathname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->pathname().data(), static_cast<int>(this->pathname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.Fs_record.pathname"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 unix_permissions = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &unix_permissions_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .proto.File_type type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::proto::File_type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 modified_seconds = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &modified_seconds_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .proto.Ref ref = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_ref()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string symlink_target = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_symlink_target()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->symlink_target().data(), static_cast<int>(this->symlink_target().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.Fs_record.symlink_target"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string posix_acl = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_posix_acl()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->posix_acl().data(), static_cast<int>(this->posix_acl().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.Fs_record.posix_acl"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string posix_default_acl = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_posix_default_acl()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->posix_default_acl().data(), static_cast<int>(this->posix_default_acl().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.Fs_record.posix_default_acl"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Fs_record)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Fs_record)
  return false;
#undef DO_
}

void Fs_record::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Fs_record)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string pathname = 1;
  if (this->pathname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pathname().data(), static_cast<int>(this->pathname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.Fs_record.pathname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->pathname(), output);
  }

  // uint32 unix_permissions = 2;
  if (this->unix_permissions() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->unix_permissions(), output);
  }

  // .proto.File_type type = 3;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->type(), output);
  }

  // uint64 modified_seconds = 4;
  if (this->modified_seconds() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->modified_seconds(), output);
  }

  // .proto.Ref ref = 5;
  if (this->has_ref()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5, *this->ref_, output);
  }

  // string symlink_target = 6;
  if (this->symlink_target().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->symlink_target().data(), static_cast<int>(this->symlink_target().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.Fs_record.symlink_target");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->symlink_target(), output);
  }

  // string posix_acl = 7;
  if (this->posix_acl().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->posix_acl().data(), static_cast<int>(this->posix_acl().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.Fs_record.posix_acl");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->posix_acl(), output);
  }

  // string posix_default_acl = 8;
  if (this->posix_default_acl().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->posix_default_acl().data(), static_cast<int>(this->posix_default_acl().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.Fs_record.posix_default_acl");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->posix_default_acl(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.Fs_record)
}

size_t Fs_record::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Fs_record)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string pathname = 1;
  if (this->pathname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pathname());
  }

  // string symlink_target = 6;
  if (this->symlink_target().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->symlink_target());
  }

  // string posix_acl = 7;
  if (this->posix_acl().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->posix_acl());
  }

  // string posix_default_acl = 8;
  if (this->posix_default_acl().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->posix_default_acl());
  }

  // .proto.Ref ref = 5;
  if (this->has_ref()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->ref_);
  }

  // uint32 unix_permissions = 2;
  if (this->unix_permissions() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->unix_permissions());
  }

  // .proto.File_type type = 3;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // uint64 modified_seconds = 4;
  if (this->modified_seconds() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->modified_seconds());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Fs_record::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Fs_record*>(&from));
}

void Fs_record::MergeFrom(const Fs_record& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Fs_record)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.pathname().size() > 0) {

    pathname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pathname_);
  }
  if (from.symlink_target().size() > 0) {

    symlink_target_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.symlink_target_);
  }
  if (from.posix_acl().size() > 0) {

    posix_acl_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.posix_acl_);
  }
  if (from.posix_default_acl().size() > 0) {

    posix_default_acl_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.posix_default_acl_);
  }
  if (from.has_ref()) {
    mutable_ref()->::proto::Ref::MergeFrom(from.ref());
  }
  if (from.unix_permissions() != 0) {
    set_unix_permissions(from.unix_permissions());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.modified_seconds() != 0) {
    set_modified_seconds(from.modified_seconds());
  }
}

void Fs_record::CopyFrom(const Fs_record& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Fs_record)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Fs_record::IsInitialized() const {
  return true;
}

void Fs_record::Swap(Fs_record* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Fs_record::InternalSwap(Fs_record* other) {
  using std::swap;
  pathname_.Swap(&other->pathname_);
  symlink_target_.Swap(&other->symlink_target_);
  posix_acl_.Swap(&other->posix_acl_);
  posix_default_acl_.Swap(&other->posix_default_acl_);
  swap(ref_, other->ref_);
  swap(unix_permissions_, other->unix_permissions_);
  swap(type_, other->type_);
  swap(modified_seconds_, other->modified_seconds_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Fs_record::GetTypeName() const {
  return "proto.Fs_record";
}


// ===================================================================

void Fs_state::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Fs_state::kRecFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Fs_state::Fs_state()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsFs_state();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Fs_state)
}
Fs_state::Fs_state(const Fs_state& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      rec_(from.rec_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.Fs_state)
}

void Fs_state::SharedCtor() {
  _cached_size_ = 0;
}

Fs_state::~Fs_state() {
  // @@protoc_insertion_point(destructor:proto.Fs_state)
  SharedDtor();
}

void Fs_state::SharedDtor() {
}

void Fs_state::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Fs_state& Fs_state::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsFs_state();
  return *internal_default_instance();
}

Fs_state* Fs_state::New(::google::protobuf::Arena* arena) const {
  Fs_state* n = new Fs_state;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Fs_state::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Fs_state)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  rec_.Clear();
  _internal_metadata_.Clear();
}

bool Fs_state::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.Fs_state)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .proto.Fs_record rec = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_rec()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Fs_state)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Fs_state)
  return false;
#undef DO_
}

void Fs_state::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Fs_state)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .proto.Fs_record rec = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->rec_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->rec(static_cast<int>(i)), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.Fs_state)
}

size_t Fs_state::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Fs_state)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .proto.Fs_record rec = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->rec_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->rec(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Fs_state::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Fs_state*>(&from));
}

void Fs_state::MergeFrom(const Fs_state& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Fs_state)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  rec_.MergeFrom(from.rec_);
}

void Fs_state::CopyFrom(const Fs_state& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Fs_state)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Fs_state::IsInitialized() const {
  return true;
}

void Fs_state::Swap(Fs_state* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Fs_state::InternalSwap(Fs_state* other) {
  using std::swap;
  rec_.InternalSwap(&other->rec_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Fs_state::GetTypeName() const {
  return "proto.Fs_state";
}


// ===================================================================

void File_desc::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int File_desc::kNameFieldNumber;
const int File_desc::kFiltersFieldNumber;
const int File_desc::kRefsFieldNumber;
const int File_desc::kTimeCreatedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

File_desc::File_desc()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsFile_desc();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.File_desc)
}
File_desc::File_desc(const File_desc& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      filters_(from.filters_),
      refs_(from.refs_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  time_created_ = from.time_created_;
  // @@protoc_insertion_point(copy_constructor:proto.File_desc)
}

void File_desc::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_created_ = GOOGLE_ULONGLONG(0);
  _cached_size_ = 0;
}

File_desc::~File_desc() {
  // @@protoc_insertion_point(destructor:proto.File_desc)
  SharedDtor();
}

void File_desc::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void File_desc::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const File_desc& File_desc::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsFile_desc();
  return *internal_default_instance();
}

File_desc* File_desc::New(::google::protobuf::Arena* arena) const {
  File_desc* n = new File_desc;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void File_desc::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.File_desc)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  filters_.Clear();
  refs_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_created_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool File_desc::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.File_desc)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.File_desc.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .proto.Filter filters = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_filters()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .proto.Ref_count refs = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_refs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 time_created = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &time_created_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.File_desc)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.File_desc)
  return false;
#undef DO_
}

void File_desc::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.File_desc)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.File_desc.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .proto.Filter filters = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->filters_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->filters(static_cast<int>(i)), output);
  }

  // repeated .proto.Ref_count refs = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->refs_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->refs(static_cast<int>(i)), output);
  }

  // uint64 time_created = 4;
  if (this->time_created() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->time_created(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.File_desc)
}

size_t File_desc::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.File_desc)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .proto.Filter filters = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->filters_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->filters(static_cast<int>(i)));
    }
  }

  // repeated .proto.Ref_count refs = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->refs_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->refs(static_cast<int>(i)));
    }
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // uint64 time_created = 4;
  if (this->time_created() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->time_created());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void File_desc::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const File_desc*>(&from));
}

void File_desc::MergeFrom(const File_desc& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.File_desc)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  filters_.MergeFrom(from.filters_);
  refs_.MergeFrom(from.refs_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.time_created() != 0) {
    set_time_created(from.time_created());
  }
}

void File_desc::CopyFrom(const File_desc& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.File_desc)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool File_desc::IsInitialized() const {
  return true;
}

void File_desc::Swap(File_desc* other) {
  if (other == this) return;
  InternalSwap(other);
}
void File_desc::InternalSwap(File_desc* other) {
  using std::swap;
  filters_.InternalSwap(&other->filters_);
  refs_.InternalSwap(&other->refs_);
  name_.Swap(&other->name_);
  swap(time_created_, other->time_created_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string File_desc::GetTypeName() const {
  return "proto.File_desc";
}


// ===================================================================

void Ref_count::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Ref_count::kFromFieldNumber;
const int Ref_count::kToFieldNumber;
const int Ref_count::kRefCountFieldNumber;
const int Ref_count::kSpaceTakenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Ref_count::Ref_count()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsRef_count();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Ref_count)
}
Ref_count::Ref_count(const Ref_count& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&from_, &from.from_,
    static_cast<size_t>(reinterpret_cast<char*>(&space_taken_) -
    reinterpret_cast<char*>(&from_)) + sizeof(space_taken_));
  // @@protoc_insertion_point(copy_constructor:proto.Ref_count)
}

void Ref_count::SharedCtor() {
  ::memset(&from_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&space_taken_) -
      reinterpret_cast<char*>(&from_)) + sizeof(space_taken_));
  _cached_size_ = 0;
}

Ref_count::~Ref_count() {
  // @@protoc_insertion_point(destructor:proto.Ref_count)
  SharedDtor();
}

void Ref_count::SharedDtor() {
}

void Ref_count::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Ref_count& Ref_count::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsRef_count();
  return *internal_default_instance();
}

Ref_count* Ref_count::New(::google::protobuf::Arena* arena) const {
  Ref_count* n = new Ref_count;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Ref_count::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Ref_count)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&from_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&space_taken_) -
      reinterpret_cast<char*>(&from_)) + sizeof(space_taken_));
  _internal_metadata_.Clear();
}

bool Ref_count::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.Ref_count)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 from = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &from_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 to = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &to_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 ref_count = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &ref_count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 space_taken = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &space_taken_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Ref_count)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Ref_count)
  return false;
#undef DO_
}

void Ref_count::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Ref_count)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 from = 1;
  if (this->from() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->from(), output);
  }

  // uint64 to = 2;
  if (this->to() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->to(), output);
  }

  // uint64 ref_count = 3;
  if (this->ref_count() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->ref_count(), output);
  }

  // uint64 space_taken = 4;
  if (this->space_taken() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->space_taken(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.Ref_count)
}

size_t Ref_count::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Ref_count)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // uint64 from = 1;
  if (this->from() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->from());
  }

  // uint64 to = 2;
  if (this->to() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->to());
  }

  // uint64 ref_count = 3;
  if (this->ref_count() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->ref_count());
  }

  // uint64 space_taken = 4;
  if (this->space_taken() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->space_taken());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Ref_count::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Ref_count*>(&from));
}

void Ref_count::MergeFrom(const Ref_count& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Ref_count)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.from() != 0) {
    set_from(from.from());
  }
  if (from.to() != 0) {
    set_to(from.to());
  }
  if (from.ref_count() != 0) {
    set_ref_count(from.ref_count());
  }
  if (from.space_taken() != 0) {
    set_space_taken(from.space_taken());
  }
}

void Ref_count::CopyFrom(const Ref_count& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Ref_count)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ref_count::IsInitialized() const {
  return true;
}

void Ref_count::Swap(Ref_count* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Ref_count::InternalSwap(Ref_count* other) {
  using std::swap;
  swap(from_, other->from_);
  swap(to_, other->to_);
  swap(ref_count_, other->ref_count_);
  swap(space_taken_, other->space_taken_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Ref_count::GetTypeName() const {
  return "proto.Ref_count";
}


// ===================================================================

void Catalogue::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Catalogue::kUsedFilesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Catalogue::Catalogue()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsCatalogue();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Catalogue)
}
Catalogue::Catalogue(const Catalogue& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      used_files_(from.used_files_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.Catalogue)
}

void Catalogue::SharedCtor() {
  _cached_size_ = 0;
}

Catalogue::~Catalogue() {
  // @@protoc_insertion_point(destructor:proto.Catalogue)
  SharedDtor();
}

void Catalogue::SharedDtor() {
}

void Catalogue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Catalogue& Catalogue::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsCatalogue();
  return *internal_default_instance();
}

Catalogue* Catalogue::New(::google::protobuf::Arena* arena) const {
  Catalogue* n = new Catalogue;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Catalogue::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Catalogue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  used_files_.Clear();
  _internal_metadata_.Clear();
}

bool Catalogue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.Catalogue)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .proto.File_desc used_files = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_used_files()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Catalogue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Catalogue)
  return false;
#undef DO_
}

void Catalogue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Catalogue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .proto.File_desc used_files = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->used_files_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->used_files(static_cast<int>(i)), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.Catalogue)
}

size_t Catalogue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Catalogue)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .proto.File_desc used_files = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->used_files_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->used_files(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Catalogue::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Catalogue*>(&from));
}

void Catalogue::MergeFrom(const Catalogue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Catalogue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  used_files_.MergeFrom(from.used_files_);
}

void Catalogue::CopyFrom(const Catalogue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Catalogue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Catalogue::IsInitialized() const {
  return true;
}

void Catalogue::Swap(Catalogue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Catalogue::InternalSwap(Catalogue* other) {
  using std::swap;
  used_files_.InternalSwap(&other->used_files_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Catalogue::GetTypeName() const {
  return "proto.Catalogue";
}


// ===================================================================

void Catalog_header::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Catalog_header::kFiltersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Catalog_header::Catalog_header()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_format_2eproto::InitDefaultsCatalog_header();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Catalog_header)
}
Catalog_header::Catalog_header(const Catalog_header& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      filters_(from.filters_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.Catalog_header)
}

void Catalog_header::SharedCtor() {
  _cached_size_ = 0;
}

Catalog_header::~Catalog_header() {
  // @@protoc_insertion_point(destructor:proto.Catalog_header)
  SharedDtor();
}

void Catalog_header::SharedDtor() {
}

void Catalog_header::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Catalog_header& Catalog_header::default_instance() {
  ::protobuf_format_2eproto::InitDefaultsCatalog_header();
  return *internal_default_instance();
}

Catalog_header* Catalog_header::New(::google::protobuf::Arena* arena) const {
  Catalog_header* n = new Catalog_header;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Catalog_header::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Catalog_header)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  filters_.Clear();
  _internal_metadata_.Clear();
}

bool Catalog_header::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:proto.Catalog_header)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .proto.Filter filters = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_filters()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Catalog_header)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Catalog_header)
  return false;
#undef DO_
}

void Catalog_header::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Catalog_header)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .proto.Filter filters = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->filters_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->filters(static_cast<int>(i)), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:proto.Catalog_header)
}

size_t Catalog_header::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Catalog_header)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .proto.Filter filters = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->filters_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->filters(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Catalog_header::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Catalog_header*>(&from));
}

void Catalog_header::MergeFrom(const Catalog_header& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Catalog_header)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  filters_.MergeFrom(from.filters_);
}

void Catalog_header::CopyFrom(const Catalog_header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Catalog_header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Catalog_header::IsInitialized() const {
  return true;
}

void Catalog_header::Swap(Catalog_header* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Catalog_header::InternalSwap(Catalog_header* other) {
  using std::swap;
  filters_.InternalSwap(&other->filters_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Catalog_header::GetTypeName() const {
  return "proto.Catalog_header";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto

// @@protoc_insertion_point(global_scope)
