name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v1
    #- name: prepare
    #  run: 
    #    sudo apt-get install docker.io
    - name: build
      run: |
        ./docker-build.sh
        #strip archivarius

    - uses: actions/upload-artifact@v3
      with:
        name: archivarius
        path: docker-build-out/archivarius
