name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: 
        sudo apt-get install libacl1-dev libzstd1-dev clang-9 libc++-9-dev lld-9 libc++abi-9-dev 
    - name: configure
      run: 
        mkdir build &&
        cd build &&
        CXX=clang++-9 CC=clang-9 cmake -DARCHIVARIUS_STATIC_BUILD=ON ..
    - name: build
      #run: cd build && cmake --build . --target archivarius
      run: cd build && make VERBOSE=1 archivarius

    - uses: actions/upload-artifact@v1
      with:
        name: archivarius
        path: build/archivarius
