name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: 
        mkdir build1 &&
        cd build1 &&
        CXX=clang++-8 CC=clang-8 cmake ..
    - name: make
      run: make archivarius

